import { Link } from 'react-router-dom';
import Icon from '../../components/catalog/Icon.jsx';
import { HeritageFilm } from '../../components/catalog/EditorialMedia.jsx';
import { media } from '../../constants/editorialMedia.js';
import PublishedPage from '../stories/PublishedPage.jsx';

export function AboutPage() {
  return <><section className="page-masthead"><p className="eyebrow">VỀ TRO & LAM</p><h1>Hành trình đến gần hơn với gốm.</h1><p>Gốm Chu Đậu cho không gian sống, cho những điều thân thuộc và cho những dịp trao tặng.</p></section><section className="editorial-intro atelier-section"><div><p className="eyebrow">MỘT HÀNH TRÌNH ĐANG TIẾP NỐI</p><h2>Đưa gốm đến gần<br />hơn với mỗi ngày.</h2><p>TRO & LAM kể câu chuyện về gốm Chu Đậu qua những điều gần gũi: một góc trà, một vật phẩm cho không gian sống, hay món quà dành cho dịp cần sự trân trọng.</p><p>Hai dòng Lifestyle và Diplomacy mở ra hai cách khám phá. Hãy bắt đầu từ điều bạn đang tìm kiếm.</p><Link className="text-link" to="/san-pham">Tìm món gốm của bạn <Icon name="arrow" size={18} /></Link></div><figure className="editorial-intro__image"><img src={media.hands} alt="Bàn tay tạo hình gốm trên bàn xoay — ảnh minh họa nghề gốm" loading="lazy" /><figcaption>Ảnh nghề gốm · Earl Wilcox / Unsplash</figcaption></figure></section><section className="journey-links atelier-section" aria-label="Hai dòng sản phẩm TRO & LAM"><article><span className="value-number">01 / LIFESTYLE</span><h2>Gốm trong đời sống</h2><p>Lư xông trầm mini, hũ trà và bộ chén độc ẩm là những gợi ý cho không gian sống và góc trà.</p><Link className="text-link" to="/bo-suu-tap/lifestyle">Khám phá Lifestyle <Icon name="arrow" size={18} /></Link></article><article><span className="value-number">02 / DIPLOMACY</span><h2>Gốm trao tặng</h2><p>Khám phá các dáng bình trong dòng Diplomacy và gửi yêu cầu tư vấn cho dịp tặng của bạn.</p><Link className="text-link" to="/bo-suu-tap/diplomacy">Khám phá Diplomacy <Icon name="arrow" size={18} /></Link></article></section></>;
}
function StoryIntroduction() {
  return <section className="editorial-intro atelier-section"><figure className="editorial-intro__image"><img src={media.heritage} alt="Ảnh tư liệu bình gốm hoa lam Chu Đậu" loading="lazy" /><figcaption>Bình Chu Đậu · Marie-Lan Nguyen / Wikimedia Commons</figcaption></figure><div><p className="eyebrow">GÓC CẢM HỨNG</p><h2>Một sắc lam.<br />Nhiều cách cảm nhận.</h2><p>Một dáng bình, một nét vẽ, một màu men. Đôi khi, chỉ cần dừng lại lâu hơn một chút để tìm thấy điều khiến mình yêu gốm.</p><p>Ghé xem phim tư liệu bên dưới, hoặc khám phá gốm trong không gian sống và những dịp trao tặng cùng TRO & LAM.</p><Link className="text-link" to="/san-pham">Khám phá sản phẩm <Icon name="arrow" size={18} /></Link></div></section>;
}
export function StoriesLandingPage() {
  return <><section className="page-masthead"><p className="eyebrow">GÓC CÂU CHUYỆN</p><h1>Chậm lại, nghe gốm kể.</h1><p>Những góc nhìn về gốm, vẻ đẹp của những điều bình dị và cảm hứng cho đời sống.</p></section><PublishedPage pageSlug="cau-chuyen" fallback={<StoryIntroduction />} /><HeritageFilm /><section className="closing-note atelier-section"><h2>Câu chuyện tiếp theo,<br />bắt đầu từ bạn.</h2><Link className="text-link" to="/lien-he">Chia sẻ cùng TRO & LAM <Icon name="arrow" size={18} /></Link></section></>;
}
export function MediaCreditsPage() {
  return <><section className="page-masthead"><p className="eyebrow">TÔN TRỌNG NGƯỜI SÁNG TẠO</p><h1>Nguồn hình ảnh & phim</h1><p>Ảnh tư liệu và ảnh nghề gốm minh họa cho nội dung biên tập, không phải ảnh sản phẩm bán trong danh mục.</p></section><div className="media-credits atelier-section"><article><h2>Video banner — Tro &amp; Lam</h2><p>Reel 30 giây do người dùng cung cấp từ kênh Tro &amp; Lam. Nguồn trong bài đăng: Báo Nhân Dân, VTV5, Về Làng. Bản banner được nén, tắt âm thanh và phát lặp.</p><a href="https://www.facebook.com/reel/1134937905628694" target="_blank" rel="noreferrer">Xem bài đăng gốc của Tro &amp; Lam</a></article><article><h2>Đôi bàn tay trên bàn xoay</h2><p>Ảnh: Earl Wilcox / Unsplash. Ảnh nghề gốm, không xác định là xưởng Chu Đậu hay xưởng của TRO & LAM. Hiển thị cắt khung và phủ màu theo bố cục.</p><a href="https://unsplash.com/photos/person-holding-round-brown-wooden-plate-88DYIsFhuSs" target="_blank" rel="noreferrer">Ảnh gốc trên Unsplash</a> · <a href="https://unsplash.com/license" target="_blank" rel="noreferrer">Giấy phép Unsplash</a></article><article><h2>Bình gốm hoa lam Chu Đậu</h2><p>© Marie-Lan Nguyen / Wikimedia Commons / CC BY 2.5. Hiện vật thuộc Bảo tàng Lịch sử Việt Nam. Hiển thị cắt khung theo bố cục; đây là ảnh tư liệu, không phải sản phẩm của TRO & LAM.</p><a href="https://commons.wikimedia.org/wiki/File:Blue_and_white_Chu_Dau_jar_NMVH_EDAV.jpg" target="_blank" rel="noreferrer">Ảnh và thông tin gốc</a> · <a href="https://creativecommons.org/licenses/by/2.5/" target="_blank" rel="noreferrer">CC BY 2.5</a></article><article><h2>Không gian trà và bình gốm</h2><p>Ảnh cảm hứng từ Unsplash, không phải ảnh SKU hay minh chứng xuất xứ Chu Đậu. Ảnh được cắt khung theo bố cục.</p><a href="https://unsplash.com/photos/two-bowls-of-tea-sit-on-a-wooden-table-STLZpvkqaMY" target="_blank" rel="noreferrer">Hai chén trà — ảnh gốc</a> · <a href="https://unsplash.com/photos/two-white-vases-with-red-flowers-in-them-7T12an8w_hQ" target="_blank" rel="noreferrer">Bình gốm — Mary Skrynnikova</a> · <a href="https://unsplash.com/license" target="_blank" rel="noreferrer">Giấy phép Unsplash</a></article><article><h2>Sức sống gốm Chu Đậu</h2><p>Phim: VTV4, đăng ngày 16/11/2020. Phát từ YouTube khi bạn chọn xem; bản quyền thuộc đơn vị sản xuất. TRO & LAM không lưu trữ hay chỉnh sửa phim.</p><a href="https://www.youtube.com/watch?v=AVtL9Y3ndTY" target="_blank" rel="noreferrer">Xem phim gốc của VTV4</a></article></div></>;
}
